###################################################################

# Created by write_sdc on Thu Dec 21 17:32:55 2023

###################################################################
set sdc_version 1.8

set_units -time ns -resistance kOhm -capacitance pF -power mW -voltage V       \
-current mA
set_operating_conditions typical -library gscl45nm
set_max_area 50000
set_max_transition 2000 [current_design]
set_fanout_load 0.001 [get_ports {dm_dout[31]}]
set_fanout_load 0.001 [get_ports {dm_dout[30]}]
set_fanout_load 0.001 [get_ports {dm_dout[29]}]
set_fanout_load 0.001 [get_ports {dm_dout[28]}]
set_fanout_load 0.001 [get_ports {dm_dout[27]}]
set_fanout_load 0.001 [get_ports {dm_dout[26]}]
set_fanout_load 0.001 [get_ports {dm_dout[25]}]
set_fanout_load 0.001 [get_ports {dm_dout[24]}]
set_fanout_load 0.001 [get_ports {dm_dout[23]}]
set_fanout_load 0.001 [get_ports {dm_dout[22]}]
set_fanout_load 0.001 [get_ports {dm_dout[21]}]
set_fanout_load 0.001 [get_ports {dm_dout[20]}]
set_fanout_load 0.001 [get_ports {dm_dout[19]}]
set_fanout_load 0.001 [get_ports {dm_dout[18]}]
set_fanout_load 0.001 [get_ports {dm_dout[17]}]
set_fanout_load 0.001 [get_ports {dm_dout[16]}]
set_fanout_load 0.001 [get_ports {dm_dout[15]}]
set_fanout_load 0.001 [get_ports {dm_dout[14]}]
set_fanout_load 0.001 [get_ports {dm_dout[13]}]
set_fanout_load 0.001 [get_ports {dm_dout[12]}]
set_fanout_load 0.001 [get_ports {dm_dout[11]}]
set_fanout_load 0.001 [get_ports {dm_dout[10]}]
set_fanout_load 0.001 [get_ports {dm_dout[9]}]
set_fanout_load 0.001 [get_ports {dm_dout[8]}]
set_fanout_load 0.001 [get_ports {dm_dout[7]}]
set_fanout_load 0.001 [get_ports {dm_dout[6]}]
set_fanout_load 0.001 [get_ports {dm_dout[5]}]
set_fanout_load 0.001 [get_ports {dm_dout[4]}]
set_fanout_load 0.001 [get_ports {dm_dout[3]}]
set_fanout_load 0.001 [get_ports {dm_dout[2]}]
set_fanout_load 0.001 [get_ports {dm_dout[1]}]
set_fanout_load 0.001 [get_ports {dm_dout[0]}]
set_load -pin_load 0.01 [get_ports {dm_dout[31]}]
set_load -pin_load 0.01 [get_ports {dm_dout[30]}]
set_load -pin_load 0.01 [get_ports {dm_dout[29]}]
set_load -pin_load 0.01 [get_ports {dm_dout[28]}]
set_load -pin_load 0.01 [get_ports {dm_dout[27]}]
set_load -pin_load 0.01 [get_ports {dm_dout[26]}]
set_load -pin_load 0.01 [get_ports {dm_dout[25]}]
set_load -pin_load 0.01 [get_ports {dm_dout[24]}]
set_load -pin_load 0.01 [get_ports {dm_dout[23]}]
set_load -pin_load 0.01 [get_ports {dm_dout[22]}]
set_load -pin_load 0.01 [get_ports {dm_dout[21]}]
set_load -pin_load 0.01 [get_ports {dm_dout[20]}]
set_load -pin_load 0.01 [get_ports {dm_dout[19]}]
set_load -pin_load 0.01 [get_ports {dm_dout[18]}]
set_load -pin_load 0.01 [get_ports {dm_dout[17]}]
set_load -pin_load 0.01 [get_ports {dm_dout[16]}]
set_load -pin_load 0.01 [get_ports {dm_dout[15]}]
set_load -pin_load 0.01 [get_ports {dm_dout[14]}]
set_load -pin_load 0.01 [get_ports {dm_dout[13]}]
set_load -pin_load 0.01 [get_ports {dm_dout[12]}]
set_load -pin_load 0.01 [get_ports {dm_dout[11]}]
set_load -pin_load 0.01 [get_ports {dm_dout[10]}]
set_load -pin_load 0.01 [get_ports {dm_dout[9]}]
set_load -pin_load 0.01 [get_ports {dm_dout[8]}]
set_load -pin_load 0.01 [get_ports {dm_dout[7]}]
set_load -pin_load 0.01 [get_ports {dm_dout[6]}]
set_load -pin_load 0.01 [get_ports {dm_dout[5]}]
set_load -pin_load 0.01 [get_ports {dm_dout[4]}]
set_load -pin_load 0.01 [get_ports {dm_dout[3]}]
set_load -pin_load 0.01 [get_ports {dm_dout[2]}]
set_load -pin_load 0.01 [get_ports {dm_dout[1]}]
set_load -pin_load 0.01 [get_ports {dm_dout[0]}]
set_max_capacitance 50000 [get_ports {dm_dout[31]}]
set_max_capacitance 50000 [get_ports {dm_dout[30]}]
set_max_capacitance 50000 [get_ports {dm_dout[29]}]
set_max_capacitance 50000 [get_ports {dm_dout[28]}]
set_max_capacitance 50000 [get_ports {dm_dout[27]}]
set_max_capacitance 50000 [get_ports {dm_dout[26]}]
set_max_capacitance 50000 [get_ports {dm_dout[25]}]
set_max_capacitance 50000 [get_ports {dm_dout[24]}]
set_max_capacitance 50000 [get_ports {dm_dout[23]}]
set_max_capacitance 50000 [get_ports {dm_dout[22]}]
set_max_capacitance 50000 [get_ports {dm_dout[21]}]
set_max_capacitance 50000 [get_ports {dm_dout[20]}]
set_max_capacitance 50000 [get_ports {dm_dout[19]}]
set_max_capacitance 50000 [get_ports {dm_dout[18]}]
set_max_capacitance 50000 [get_ports {dm_dout[17]}]
set_max_capacitance 50000 [get_ports {dm_dout[16]}]
set_max_capacitance 50000 [get_ports {dm_dout[15]}]
set_max_capacitance 50000 [get_ports {dm_dout[14]}]
set_max_capacitance 50000 [get_ports {dm_dout[13]}]
set_max_capacitance 50000 [get_ports {dm_dout[12]}]
set_max_capacitance 50000 [get_ports {dm_dout[11]}]
set_max_capacitance 50000 [get_ports {dm_dout[10]}]
set_max_capacitance 50000 [get_ports {dm_dout[9]}]
set_max_capacitance 50000 [get_ports {dm_dout[8]}]
set_max_capacitance 50000 [get_ports {dm_dout[7]}]
set_max_capacitance 50000 [get_ports {dm_dout[6]}]
set_max_capacitance 50000 [get_ports {dm_dout[5]}]
set_max_capacitance 50000 [get_ports {dm_dout[4]}]
set_max_capacitance 50000 [get_ports {dm_dout[3]}]
set_max_capacitance 50000 [get_ports {dm_dout[2]}]
set_max_capacitance 50000 [get_ports {dm_dout[1]}]
set_max_capacitance 50000 [get_ports {dm_dout[0]}]
set_max_fanout 100 [get_ports clk]
set_max_fanout 100 [get_ports rst]
set_max_fanout 100 [get_ports im_web]
set_max_fanout 100 [get_ports {im_din[31]}]
set_max_fanout 100 [get_ports {im_din[30]}]
set_max_fanout 100 [get_ports {im_din[29]}]
set_max_fanout 100 [get_ports {im_din[28]}]
set_max_fanout 100 [get_ports {im_din[27]}]
set_max_fanout 100 [get_ports {im_din[26]}]
set_max_fanout 100 [get_ports {im_din[25]}]
set_max_fanout 100 [get_ports {im_din[24]}]
set_max_fanout 100 [get_ports {im_din[23]}]
set_max_fanout 100 [get_ports {im_din[22]}]
set_max_fanout 100 [get_ports {im_din[21]}]
set_max_fanout 100 [get_ports {im_din[20]}]
set_max_fanout 100 [get_ports {im_din[19]}]
set_max_fanout 100 [get_ports {im_din[18]}]
set_max_fanout 100 [get_ports {im_din[17]}]
set_max_fanout 100 [get_ports {im_din[16]}]
set_max_fanout 100 [get_ports {im_din[15]}]
set_max_fanout 100 [get_ports {im_din[14]}]
set_max_fanout 100 [get_ports {im_din[13]}]
set_max_fanout 100 [get_ports {im_din[12]}]
set_max_fanout 100 [get_ports {im_din[11]}]
set_max_fanout 100 [get_ports {im_din[10]}]
set_max_fanout 100 [get_ports {im_din[9]}]
set_max_fanout 100 [get_ports {im_din[8]}]
set_max_fanout 100 [get_ports {im_din[7]}]
set_max_fanout 100 [get_ports {im_din[6]}]
set_max_fanout 100 [get_ports {im_din[5]}]
set_max_fanout 100 [get_ports {im_din[4]}]
set_max_fanout 100 [get_ports {im_din[3]}]
set_max_fanout 100 [get_ports {im_din[2]}]
set_max_fanout 100 [get_ports {im_din[1]}]
set_max_fanout 100 [get_ports {im_din[0]}]
create_clock [get_ports clk]  -period 2.6  -waveform {0 1.3}
set_clock_latency 0.01  [get_clocks clk]
set_input_delay -clock clk  0.02  [get_ports clk]
set_input_delay -clock clk  0.02  [get_ports rst]
set_input_delay -clock clk  0.02  [get_ports im_web]
set_input_delay -clock clk  0.02  [get_ports {im_din[31]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[30]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[29]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[28]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[27]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[26]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[25]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[24]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[23]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[22]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[21]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[20]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[19]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[18]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[17]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[16]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[15]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[14]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[13]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[12]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[11]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[10]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[9]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[8]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[7]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[6]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[5]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[4]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[3]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[2]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[1]}]
set_input_delay -clock clk  0.02  [get_ports {im_din[0]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[31]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[30]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[29]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[28]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[27]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[26]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[25]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[24]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[23]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[22]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[21]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[20]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[19]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[18]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[17]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[16]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[15]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[14]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[13]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[12]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[11]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[10]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[9]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[8]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[7]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[6]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[5]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[4]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[3]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[2]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[1]}]
set_output_delay -clock clk  0.01  [get_ports {dm_dout[0]}]
set_drive 0.01  [get_ports clk]
set_drive 0.01  [get_ports rst]
set_drive 0.01  [get_ports im_web]
set_drive 0.01  [get_ports {im_din[31]}]
set_drive 0.01  [get_ports {im_din[30]}]
set_drive 0.01  [get_ports {im_din[29]}]
set_drive 0.01  [get_ports {im_din[28]}]
set_drive 0.01  [get_ports {im_din[27]}]
set_drive 0.01  [get_ports {im_din[26]}]
set_drive 0.01  [get_ports {im_din[25]}]
set_drive 0.01  [get_ports {im_din[24]}]
set_drive 0.01  [get_ports {im_din[23]}]
set_drive 0.01  [get_ports {im_din[22]}]
set_drive 0.01  [get_ports {im_din[21]}]
set_drive 0.01  [get_ports {im_din[20]}]
set_drive 0.01  [get_ports {im_din[19]}]
set_drive 0.01  [get_ports {im_din[18]}]
set_drive 0.01  [get_ports {im_din[17]}]
set_drive 0.01  [get_ports {im_din[16]}]
set_drive 0.01  [get_ports {im_din[15]}]
set_drive 0.01  [get_ports {im_din[14]}]
set_drive 0.01  [get_ports {im_din[13]}]
set_drive 0.01  [get_ports {im_din[12]}]
set_drive 0.01  [get_ports {im_din[11]}]
set_drive 0.01  [get_ports {im_din[10]}]
set_drive 0.01  [get_ports {im_din[9]}]
set_drive 0.01  [get_ports {im_din[8]}]
set_drive 0.01  [get_ports {im_din[7]}]
set_drive 0.01  [get_ports {im_din[6]}]
set_drive 0.01  [get_ports {im_din[5]}]
set_drive 0.01  [get_ports {im_din[4]}]
set_drive 0.01  [get_ports {im_din[3]}]
set_drive 0.01  [get_ports {im_din[2]}]
set_drive 0.01  [get_ports {im_din[1]}]
set_drive 0.01  [get_ports {im_din[0]}]
